//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHost_using_WCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllWaveFormNames", ReplyAction="http://tempuri.org/IService1/iGetAllWaveFormNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAllWaveFormNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllWaveFormNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllWaveForm", ReplyAction="http://tempuri.org/IService1/iGetAllWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAllWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllWaveForm(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetWaveForm", ReplyAction="http://tempuri.org/IService1/iGetWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.WaveForm iGetWaveForm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddWaveForm", ReplyAction="http://tempuri.org/IService1/iAddWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iAddWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddWaveForm(TranmitterLib.WaveForm waveform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelWaveForm", ReplyAction="http://tempuri.org/IService1/iDelWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iDelWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelWaveForm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateWaveForm", ReplyAction="http://tempuri.org/IService1/iUpdateWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iUpdateWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateWaveForm(TranmitterLib.WaveForm waveform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllAntennaNames", ReplyAction="http://tempuri.org/IService1/iGetAllAntennaNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAllAntennaNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllAntennaNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllAntenna", ReplyAction="http://tempuri.org/IService1/iGetAllAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAllAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllAntenna(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAntenna", ReplyAction="http://tempuri.org/IService1/iGetAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.Antenna iGetAntenna(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddAntenna", ReplyAction="http://tempuri.org/IService1/iAddAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iAddAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddAntenna(TranmitterLib.Antenna antenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelAntenna", ReplyAction="http://tempuri.org/IService1/iDelAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iDelAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelAntenna(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateAntenna", ReplyAction="http://tempuri.org/IService1/iUpdateAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iUpdateAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateAntenna(TranmitterLib.Antenna antenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllTransmitter", ReplyAction="http://tempuri.org/IService1/iGetAllTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetAllTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllTransmitter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTransmitter", ReplyAction="http://tempuri.org/IService1/iGetTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.Transmitter iGetTransmitter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddTransmitter", ReplyAction="http://tempuri.org/IService1/iAddTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iAddTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddTransmitter(TranmitterLib.Transmitter transmitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelTransmitter", ReplyAction="http://tempuri.org/IService1/iDelTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iDelTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelTransmitter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateTransmitter", ReplyAction="http://tempuri.org/IService1/iUpdateTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iUpdateTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateTransmitter(TranmitterLib.Transmitter transmitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTerNames", ReplyAction="http://tempuri.org/IService1/iGetTerNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetTerNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetTerNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTer", ReplyAction="http://tempuri.org/IService1/iGetTerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetTerWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.TerInfo iGetTer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddTerInfo", ReplyAction="http://tempuri.org/IService1/iAddTerInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iAddTerInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddTerInfo(TranmitterLib.TerInfo terinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelTerInfo", ReplyAction="http://tempuri.org/IService1/iDelTerInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iDelTerInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelTerInfo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatTables", ReplyAction="http://tempuri.org/IService1/CreatTablesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/CreatTablesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void CreatTables(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/GetDataWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string GetData(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutData", ReplyAction="http://tempuri.org/IService1/PutDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/PutDataWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void PutData(string path, string name, string putStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetMinTaskID", ReplyAction="http://tempuri.org/IService1/iGetMinTaskIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetMinTaskIDWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.TaskInfo iGetMinTaskID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetFilePath", ReplyAction="http://tempuri.org/IService1/iGetFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetFilePathWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetFilePath(string[] filenames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iSetTaskState", ReplyAction="http://tempuri.org/IService1/iSetTaskStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iSetTaskStateWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iSetTaskState(int TaskID, short state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetProjectInfo", ReplyAction="http://tempuri.org/IService1/iGetProjectInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetProjectInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        TranmitterLib.ProjectInfo[] iGetProjectInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTaskResultDir", ReplyAction="http://tempuri.org/IService1/iGetTaskResultDirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetTaskResultDirWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string iGetTaskResultDir(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetResultFileNames", ReplyAction="http://tempuri.org/IService1/iGetResultFileNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetResultFileNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetResultFileNames(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetResultDirNames", ReplyAction="http://tempuri.org/IService1/iGetResultDirNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iGetResultDirNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetResultDirNames(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelProject", ReplyAction="http://tempuri.org/IService1/iDelProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/iDelProjectWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelProject(string proname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HeartBeat", ReplyAction="http://tempuri.org/IService1/HeartBeatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.WcfException), Action="http://tempuri.org/IService1/HeartBeatWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void HeartBeat(System.Guid guid, string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ServiceHost_using_WCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceHost_using_WCF.ServiceReference1.IService1>, ServiceHost_using_WCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] iGetAllWaveFormNames() {
            return base.Channel.iGetAllWaveFormNames();
        }
        
        public string[] iGetAllWaveForm(string type) {
            return base.Channel.iGetAllWaveForm(type);
        }
        
        public TranmitterLib.WaveForm iGetWaveForm(string name) {
            return base.Channel.iGetWaveForm(name);
        }
        
        public void iAddWaveForm(TranmitterLib.WaveForm waveform) {
            base.Channel.iAddWaveForm(waveform);
        }
        
        public void iDelWaveForm(string name) {
            base.Channel.iDelWaveForm(name);
        }
        
        public void iUpdateWaveForm(TranmitterLib.WaveForm waveform) {
            base.Channel.iUpdateWaveForm(waveform);
        }
        
        public string[] iGetAllAntennaNames() {
            return base.Channel.iGetAllAntennaNames();
        }
        
        public string[] iGetAllAntenna(string type) {
            return base.Channel.iGetAllAntenna(type);
        }
        
        public TranmitterLib.Antenna iGetAntenna(string name) {
            return base.Channel.iGetAntenna(name);
        }
        
        public void iAddAntenna(TranmitterLib.Antenna antenna) {
            base.Channel.iAddAntenna(antenna);
        }
        
        public void iDelAntenna(string name) {
            base.Channel.iDelAntenna(name);
        }
        
        public void iUpdateAntenna(TranmitterLib.Antenna antenna) {
            base.Channel.iUpdateAntenna(antenna);
        }
        
        public string[] iGetAllTransmitter() {
            return base.Channel.iGetAllTransmitter();
        }
        
        public TranmitterLib.Transmitter iGetTransmitter(string name) {
            return base.Channel.iGetTransmitter(name);
        }
        
        public void iAddTransmitter(TranmitterLib.Transmitter transmitter) {
            base.Channel.iAddTransmitter(transmitter);
        }
        
        public void iDelTransmitter(string name) {
            base.Channel.iDelTransmitter(name);
        }
        
        public void iUpdateTransmitter(TranmitterLib.Transmitter transmitter) {
            base.Channel.iUpdateTransmitter(transmitter);
        }
        
        public string[] iGetTerNames() {
            return base.Channel.iGetTerNames();
        }
        
        public TranmitterLib.TerInfo iGetTer(string name) {
            return base.Channel.iGetTer(name);
        }
        
        public void iAddTerInfo(TranmitterLib.TerInfo terinfo) {
            base.Channel.iAddTerInfo(terinfo);
        }
        
        public void iDelTerInfo(string name) {
            base.Channel.iDelTerInfo(name);
        }
        
        public void CreatTables(string path) {
            base.Channel.CreatTables(path);
        }
        
        public string GetData(string path) {
            return base.Channel.GetData(path);
        }
        
        public void PutData(string path, string name, string putStr) {
            base.Channel.PutData(path, name, putStr);
        }
        
        public TranmitterLib.TaskInfo iGetMinTaskID() {
            return base.Channel.iGetMinTaskID();
        }
        
        public string[] iGetFilePath(string[] filenames) {
            return base.Channel.iGetFilePath(filenames);
        }
        
        public void iSetTaskState(int TaskID, short state) {
            base.Channel.iSetTaskState(TaskID, state);
        }
        
        public TranmitterLib.ProjectInfo[] iGetProjectInfo() {
            return base.Channel.iGetProjectInfo();
        }
        
        public string iGetTaskResultDir(int TaskID) {
            return base.Channel.iGetTaskResultDir(TaskID);
        }
        
        public string[] iGetResultFileNames(string path) {
            return base.Channel.iGetResultFileNames(path);
        }
        
        public string[] iGetResultDirNames(string path) {
            return base.Channel.iGetResultDirNames(path);
        }
        
        public void iDelProject(string proname) {
            base.Channel.iDelProject(proname);
        }
        
        public void HeartBeat(System.Guid guid, string ip) {
            base.Channel.HeartBeat(guid, ip);
        }
    }
}
