//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaveForm", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class WaveForm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double BandWidthField;
        
        private System.Nullable<double> EndFrequencyField;
        
        private string FreChangeRateField;
        
        private double FrequencyField;
        
        private string NameField;
        
        private System.Nullable<double> PhaseField;
        
        private System.Nullable<double> RollOffFactorField;
        
        private System.Nullable<double> StartFrequencyField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double BandWidth
        {
            get
            {
                return this.BandWidthField;
            }
            set
            {
                this.BandWidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> EndFrequency
        {
            get
            {
                return this.EndFrequencyField;
            }
            set
            {
                this.EndFrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FreChangeRate
        {
            get
            {
                return this.FreChangeRateField;
            }
            set
            {
                this.FreChangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Frequency
        {
            get
            {
                return this.FrequencyField;
            }
            set
            {
                this.FrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Phase
        {
            get
            {
                return this.PhaseField;
            }
            set
            {
                this.PhaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> RollOffFactor
        {
            get
            {
                return this.RollOffFactorField;
            }
            set
            {
                this.RollOffFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> StartFrequency
        {
            get
            {
                return this.StartFrequencyField;
            }
            set
            {
                this.StartFrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Antenna", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class Antenna : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApertureDistributionField;
        
        private System.Nullable<double> BlockageRadiusField;
        
        private System.Nullable<double> EdgeTeperField;
        
        private System.Nullable<double> LengthField;
        
        private double MaxGainField;
        
        private string NameField;
        
        private System.Nullable<double> PitchField;
        
        private string PolarizationField;
        
        private System.Nullable<double> RadiusField;
        
        private double RecieveThreholdField;
        
        private double TemperatureField;
        
        private double TransmissionLossField;
        
        private string TypeField;
        
        private double VSWRField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApertureDistribution
        {
            get
            {
                return this.ApertureDistributionField;
            }
            set
            {
                this.ApertureDistributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> BlockageRadius
        {
            get
            {
                return this.BlockageRadiusField;
            }
            set
            {
                this.BlockageRadiusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> EdgeTeper
        {
            get
            {
                return this.EdgeTeperField;
            }
            set
            {
                this.EdgeTeperField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double MaxGain
        {
            get
            {
                return this.MaxGainField;
            }
            set
            {
                this.MaxGainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Pitch
        {
            get
            {
                return this.PitchField;
            }
            set
            {
                this.PitchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Polarization
        {
            get
            {
                return this.PolarizationField;
            }
            set
            {
                this.PolarizationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Radius
        {
            get
            {
                return this.RadiusField;
            }
            set
            {
                this.RadiusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double RecieveThrehold
        {
            get
            {
                return this.RecieveThreholdField;
            }
            set
            {
                this.RecieveThreholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Temperature
        {
            get
            {
                return this.TemperatureField;
            }
            set
            {
                this.TemperatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double TransmissionLoss
        {
            get
            {
                return this.TransmissionLossField;
            }
            set
            {
                this.TransmissionLossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double VSWR
        {
            get
            {
                return this.VSWRField;
            }
            set
            {
                this.VSWRField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transmitter", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class Transmitter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AntennaNameField;
        
        private string NameField;
        
        private double PowerField;
        
        private double RotateXField;
        
        private double RotateYField;
        
        private double RotateZField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AntennaName
        {
            get
            {
                return this.AntennaNameField;
            }
            set
            {
                this.AntennaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Power
        {
            get
            {
                return this.PowerField;
            }
            set
            {
                this.PowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double RotateX
        {
            get
            {
                return this.RotateXField;
            }
            set
            {
                this.RotateXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double RotateY
        {
            get
            {
                return this.RotateYField;
            }
            set
            {
                this.RotateYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double RotateZ
        {
            get
            {
                return this.RotateZField;
            }
            set
            {
                this.RotateZField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerInfo", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class TerInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double Vertex1XField;
        
        private double Vertex1YField;
        
        private double Vertex1ZField;
        
        private double Vertex2XField;
        
        private double Vertex2YField;
        
        private double Vertex2ZField;
        
        private double Vertex3XField;
        
        private double Vertex3YField;
        
        private double Vertex3ZField;
        
        private double Vertex4XField;
        
        private double Vertex4YField;
        
        private double Vertex4ZField;
        
        private double ZmaxField;
        
        private double ZminField;
        
        private string nameField;
        
        private double originXField;
        
        private double originYField;
        
        private string pathField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex1X
        {
            get
            {
                return this.Vertex1XField;
            }
            set
            {
                this.Vertex1XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex1Y
        {
            get
            {
                return this.Vertex1YField;
            }
            set
            {
                this.Vertex1YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex1Z
        {
            get
            {
                return this.Vertex1ZField;
            }
            set
            {
                this.Vertex1ZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex2X
        {
            get
            {
                return this.Vertex2XField;
            }
            set
            {
                this.Vertex2XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex2Y
        {
            get
            {
                return this.Vertex2YField;
            }
            set
            {
                this.Vertex2YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex2Z
        {
            get
            {
                return this.Vertex2ZField;
            }
            set
            {
                this.Vertex2ZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex3X
        {
            get
            {
                return this.Vertex3XField;
            }
            set
            {
                this.Vertex3XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex3Y
        {
            get
            {
                return this.Vertex3YField;
            }
            set
            {
                this.Vertex3YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex3Z
        {
            get
            {
                return this.Vertex3ZField;
            }
            set
            {
                this.Vertex3ZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex4X
        {
            get
            {
                return this.Vertex4XField;
            }
            set
            {
                this.Vertex4XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex4Y
        {
            get
            {
                return this.Vertex4YField;
            }
            set
            {
                this.Vertex4YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Vertex4Z
        {
            get
            {
                return this.Vertex4ZField;
            }
            set
            {
                this.Vertex4ZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Zmax
        {
            get
            {
                return this.ZmaxField;
            }
            set
            {
                this.ZmaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Zmin
        {
            get
            {
                return this.ZminField;
            }
            set
            {
                this.ZminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double originX
        {
            get
            {
                return this.originXField;
            }
            set
            {
                this.originXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double originY
        {
            get
            {
                return this.originYField;
            }
            set
            {
                this.originYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class TaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ProNameField;
        
        private int TaskIDField;
        
        private string[] filenamesField;
        
        private string[] filepathsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProName
        {
            get
            {
                return this.ProNameField;
            }
            set
            {
                this.ProNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskID
        {
            get
            {
                return this.TaskIDField;
            }
            set
            {
                this.TaskIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] filenames
        {
            get
            {
                return this.filenamesField;
            }
            set
            {
                this.filenamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] filepaths
        {
            get
            {
                return this.filepathsField;
            }
            set
            {
                this.filepathsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectInfo", Namespace="http://schemas.datacontract.org/2004/07/TranmitterLib")]
    public partial class ProjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> CreateTimeField;
        
        private string DirectoryField;
        
        private System.Nullable<System.DateTime> EndTimeField;
        
        private string NameField;
        
        private string PercentField;
        
        private short ProStateField;
        
        private string ResultDirectoryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Directory
        {
            get
            {
                return this.DirectoryField;
            }
            set
            {
                this.DirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Percent
        {
            get
            {
                return this.PercentField;
            }
            set
            {
                this.PercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ProState
        {
            get
            {
                return this.ProStateField;
            }
            set
            {
                this.ProStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResultDirectory
        {
            get
            {
                return this.ResultDirectoryField;
            }
            set
            {
                this.ResultDirectoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class WcfException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTaskResultDir", ReplyAction="http://tempuri.org/IService1/iGetTaskResultDirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetTaskResultDirWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string iGetTaskResultDir(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetResultFileNames", ReplyAction="http://tempuri.org/IService1/iGetResultFileNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetResultFileNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetResultFileNames(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetResultDirNames", ReplyAction="http://tempuri.org/IService1/iGetResultDirNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetResultDirNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetResultDirNames(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelProject", ReplyAction="http://tempuri.org/IService1/iDelProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iDelProjectWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelProject(string proname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HeartBeat", ReplyAction="http://tempuri.org/IService1/HeartBeatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/HeartBeatWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void HeartBeat(System.Guid guid, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllWaveFormNames", ReplyAction="http://tempuri.org/IService1/iGetAllWaveFormNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAllWaveFormNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllWaveFormNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllWaveForm", ReplyAction="http://tempuri.org/IService1/iGetAllWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAllWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllWaveForm(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetWaveForm", ReplyAction="http://tempuri.org/IService1/iGetWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.WaveForm iGetWaveForm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddWaveForm", ReplyAction="http://tempuri.org/IService1/iAddWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iAddWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddWaveForm(ServiceReference1.WaveForm waveform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelWaveForm", ReplyAction="http://tempuri.org/IService1/iDelWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iDelWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelWaveForm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateWaveForm", ReplyAction="http://tempuri.org/IService1/iUpdateWaveFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iUpdateWaveFormWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateWaveForm(ServiceReference1.WaveForm waveform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllAntennaNames", ReplyAction="http://tempuri.org/IService1/iGetAllAntennaNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAllAntennaNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllAntennaNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllAntenna", ReplyAction="http://tempuri.org/IService1/iGetAllAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAllAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllAntenna(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAntenna", ReplyAction="http://tempuri.org/IService1/iGetAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.Antenna iGetAntenna(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddAntenna", ReplyAction="http://tempuri.org/IService1/iAddAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iAddAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddAntenna(ServiceReference1.Antenna antenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelAntenna", ReplyAction="http://tempuri.org/IService1/iDelAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iDelAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelAntenna(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateAntenna", ReplyAction="http://tempuri.org/IService1/iUpdateAntennaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iUpdateAntennaWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateAntenna(ServiceReference1.Antenna antenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetAllTransmitter", ReplyAction="http://tempuri.org/IService1/iGetAllTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetAllTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetAllTransmitter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTransmitter", ReplyAction="http://tempuri.org/IService1/iGetTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.Transmitter iGetTransmitter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddTransmitter", ReplyAction="http://tempuri.org/IService1/iAddTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iAddTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddTransmitter(ServiceReference1.Transmitter transmitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelTransmitter", ReplyAction="http://tempuri.org/IService1/iDelTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iDelTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelTransmitter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iUpdateTransmitter", ReplyAction="http://tempuri.org/IService1/iUpdateTransmitterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iUpdateTransmitterWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iUpdateTransmitter(ServiceReference1.Transmitter transmitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTerNames", ReplyAction="http://tempuri.org/IService1/iGetTerNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetTerNamesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetTerNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetTer", ReplyAction="http://tempuri.org/IService1/iGetTerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetTerWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.TerInfo iGetTer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iAddTerInfo", ReplyAction="http://tempuri.org/IService1/iAddTerInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iAddTerInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iAddTerInfo(ServiceReference1.TerInfo terinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iDelTerInfo", ReplyAction="http://tempuri.org/IService1/iDelTerInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iDelTerInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iDelTerInfo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatTables", ReplyAction="http://tempuri.org/IService1/CreatTablesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/CreatTablesWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void CreatTables(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/GetDataWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string GetData(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutData", ReplyAction="http://tempuri.org/IService1/PutDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/PutDataWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void PutData(string path, string name, string putStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetMinTaskID", ReplyAction="http://tempuri.org/IService1/iGetMinTaskIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetMinTaskIDWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.TaskInfo iGetMinTaskID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetFilePath", ReplyAction="http://tempuri.org/IService1/iGetFilePathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetFilePathWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string[] iGetFilePath(string[] filenames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iSetTaskState", ReplyAction="http://tempuri.org/IService1/iSetTaskStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iSetTaskStateWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void iSetTaskState(int TaskID, short state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iGetProjectInfo", ReplyAction="http://tempuri.org/IService1/iGetProjectInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WcfException), Action="http://tempuri.org/IService1/iGetProjectInfoWcfExceptionFault", Name="WcfException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        ServiceReference1.ProjectInfo[] iGetProjectInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        public Service1Client()
        {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string iGetTaskResultDir(int TaskID)
        {
            return base.Channel.iGetTaskResultDir(TaskID);
        }
        
        public string[] iGetResultFileNames(string path)
        {
            return base.Channel.iGetResultFileNames(path);
        }
        
        public string[] iGetResultDirNames(string path)
        {
            return base.Channel.iGetResultDirNames(path);
        }
        
        public void iDelProject(string proname)
        {
            base.Channel.iDelProject(proname);
        }
        
        public void HeartBeat(System.Guid guid, string ip)
        {
            base.Channel.HeartBeat(guid, ip);
        }
        
        public string[] iGetAllWaveFormNames()
        {
            return base.Channel.iGetAllWaveFormNames();
        }
        
        public string[] iGetAllWaveForm(string type)
        {
            return base.Channel.iGetAllWaveForm(type);
        }
        
        public ServiceReference1.WaveForm iGetWaveForm(string name)
        {
            return base.Channel.iGetWaveForm(name);
        }
        
        public void iAddWaveForm(ServiceReference1.WaveForm waveform)
        {
            base.Channel.iAddWaveForm(waveform);
        }
        
        public void iDelWaveForm(string name)
        {
            base.Channel.iDelWaveForm(name);
        }
        
        public void iUpdateWaveForm(ServiceReference1.WaveForm waveform)
        {
            base.Channel.iUpdateWaveForm(waveform);
        }
        
        public string[] iGetAllAntennaNames()
        {
            return base.Channel.iGetAllAntennaNames();
        }
        
        public string[] iGetAllAntenna(string type)
        {
            return base.Channel.iGetAllAntenna(type);
        }
        
        public ServiceReference1.Antenna iGetAntenna(string name)
        {
            return base.Channel.iGetAntenna(name);
        }
        
        public void iAddAntenna(ServiceReference1.Antenna antenna)
        {
            base.Channel.iAddAntenna(antenna);
        }
        
        public void iDelAntenna(string name)
        {
            base.Channel.iDelAntenna(name);
        }
        
        public void iUpdateAntenna(ServiceReference1.Antenna antenna)
        {
            base.Channel.iUpdateAntenna(antenna);
        }
        
        public string[] iGetAllTransmitter()
        {
            return base.Channel.iGetAllTransmitter();
        }
        
        public ServiceReference1.Transmitter iGetTransmitter(string name)
        {
            return base.Channel.iGetTransmitter(name);
        }
        
        public void iAddTransmitter(ServiceReference1.Transmitter transmitter)
        {
            base.Channel.iAddTransmitter(transmitter);
        }
        
        public void iDelTransmitter(string name)
        {
            base.Channel.iDelTransmitter(name);
        }
        
        public void iUpdateTransmitter(ServiceReference1.Transmitter transmitter)
        {
            base.Channel.iUpdateTransmitter(transmitter);
        }
        
        public string[] iGetTerNames()
        {
            return base.Channel.iGetTerNames();
        }
        
        public ServiceReference1.TerInfo iGetTer(string name)
        {
            return base.Channel.iGetTer(name);
        }
        
        public void iAddTerInfo(ServiceReference1.TerInfo terinfo)
        {
            base.Channel.iAddTerInfo(terinfo);
        }
        
        public void iDelTerInfo(string name)
        {
            base.Channel.iDelTerInfo(name);
        }
        
        public void CreatTables(string path)
        {
            base.Channel.CreatTables(path);
        }
        
        public string GetData(string path)
        {
            return base.Channel.GetData(path);
        }
        
        public void PutData(string path, string name, string putStr)
        {
            base.Channel.PutData(path, name, putStr);
        }
        
        public ServiceReference1.TaskInfo iGetMinTaskID()
        {
            return base.Channel.iGetMinTaskID();
        }
        
        public string[] iGetFilePath(string[] filenames)
        {
            return base.Channel.iGetFilePath(filenames);
        }
        
        public void iSetTaskState(int TaskID, short state)
        {
            base.Channel.iSetTaskState(TaskID, state);
        }
        
        public ServiceReference1.ProjectInfo[] iGetProjectInfo()
        {
            return base.Channel.iGetProjectInfo();
        }
    }
}
